#!/bin/bash
# S.K. Sharma & Co. — VPS deploy script (Iter 644)
# Deploys the FULL latest code (includes ALL previous iterations).
#
# ═══════════ WHAT'S NEW (Iter 644) ═══════════
#
# 🔒 SALARY LOCK FIX (user bug — "Not able to Lock"):
#  * The PF/ESIC pre-lock validation popup used to live inside the
#    collapsed Configure-Batch section, so clicking Finalize & Lock on a
#    run with validation findings silently did NOTHING. The popup (and
#    the post-save Download/Mail popup) now always open.
#
# 📊 DYNAMIC ALLOWANCE / DEDUCTION COLUMNS (user bug):
#  * INCENTIVE (and every custom allowance head ticked in Firm Master →
#    Salary Structure) now gets its OWN column on the Compliance Salary
#    sheet + Excel/CSV exports — decomposed out of "Others". Totals,
#    PF/ESIC and Net are UNCHANGED.
#  * OT Hrs / OT Amt* columns now follow the "OVER TIME" toggle — hidden
#    when the firm disabled it (old runs with OT data keep the columns).
#  * TOTAL row now also prints totals under custom deduction columns.
#
# 🧰 Iter 643 (also included) — Excel-import PF ÷days fix (Firm Master
#    Fixed 26 instead of calendar 31) · frozen page headers · note-chips
#    row · 12px grid font · 642-634 earlier fixes.
#
# Run ON THE VPS as root/sksharma:
#   wget -O deploy644.sh "https://emplo-connect-1.preview.emergentagent.com/api/temp-code-bundle?token=sks-deploy-7391&kind=script"
#   bash deploy644.sh

APP_DIR=/home/sksharma/app
WEB_DIR=/var/www/sksharma
BUNDLE_URL="https://emplo-connect-1.preview.emergentagent.com/api/temp-code-bundle?token=sks-deploy-7391&kind=tar"
PIP=$APP_DIR/backend/venv/bin/pip

echo "════════════════════════════════════════════════════════════"
echo "  STEP 0 — DIAGNOSTICS (send me this block if deploy fails)"
echo "════════════════════════════════════════════════════════════"
df -h / | tail -1
free -h
sudo supervisorctl status sksharma-backend 2>/dev/null || systemctl status sksharma-backend --no-pager -l 2>/dev/null | head -5 || echo "(no backend service found)"
curl -s -m 5 http://localhost:8001/api/health && echo " <-- backend answers ✅" || echo "❌ BACKEND NOT ANSWERING"
sudo nginx -t 2>&1 | tail -1
systemctl is-active nginx && echo "nginx active ✅" || echo "❌ nginx NOT active"
ls -la $WEB_DIR/index.html 2>/dev/null || echo "❌ $WEB_DIR/index.html MISSING"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "==> 1/9 Freeing disk space (safe cache cleanup)..."
rm -rf $APP_DIR/frontend/.metro-cache $APP_DIR/frontend/.expo /tmp/metro-* /tmp/haste-* 2>/dev/null
npm cache clean --force >/dev/null 2>&1 || true
yarn cache clean >/dev/null 2>&1 || true
AVAIL_MB=$(df -m / | tail -1 | awk '{print $4}')
echo "   Free disk now: ${AVAIL_MB} MB"
if [ "$AVAIL_MB" -lt 1500 ]; then
  sudo apt-get clean 2>/dev/null || true
  sudo journalctl --vacuum-size=100M >/dev/null 2>&1 || true
  df -m / | tail -1 | awk '{print "   Free disk now: "$4" MB"}'
fi

echo "==> 2/9 Ensuring swap (prevents build OOM-kill)..."
SWAP_KB=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
if [ "$SWAP_KB" -lt 1000000 ]; then
  sudo fallocate -l 2G /swapfile 2>/dev/null || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048 status=none
  sudo chmod 600 /swapfile && sudo mkswap /swapfile >/dev/null && sudo swapon /swapfile \
    && echo "   Swap ON ✅" || echo "   (swap setup failed — continuing)"
  grep -q "/swapfile" /etc/fstab || echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab >/dev/null
else
  echo "   Swap already present ✅"
fi

echo "==> 3/9 Downloading latest code bundle (~10 MB, retries enabled)..."
rm -f /tmp/sks-latest.tar
ok=""
for i in 1 2 3 4 5; do
  if wget -c -T 60 -t 1 --show-progress -q -O /tmp/sks-latest.tar "$BUNDLE_URL"; then
    ok=1; break
  fi
  echo "   attempt $i failed — retrying in 10s..."
  sleep 10
done
if [ -z "$ok" ]; then
  curl -fSL --retry 5 --retry-delay 10 -o /tmp/sks-latest.tar "$BUNDLE_URL"
fi
if ! tar -tf /tmp/sks-latest.tar >/dev/null 2>&1; then
  echo "❌ Downloaded bundle is corrupt/incomplete. Open the portal preview URL in a browser once, wait 30s, re-run."
  exit 1
fi
echo "   Bundle OK: $(du -h /tmp/sks-latest.tar | cut -f1)"

echo "==> 4/9 Extracting into $APP_DIR (preserving .env files)..."
cp $APP_DIR/backend/.env /tmp/backend.env.bak
cp $APP_DIR/frontend/.env /tmp/frontend.env.bak 2>/dev/null || true
tar -xf /tmp/sks-latest.tar -C $APP_DIR || { echo "❌ Extract failed (disk full?) — aborting."; exit 1; }
cp /tmp/backend.env.bak $APP_DIR/backend/.env
cp /tmp/frontend.env.bak $APP_DIR/frontend/.env 2>/dev/null || true
if grep -q "^OTP_EMAIL_ENABLED=false" $APP_DIR/backend/.env; then
  sed -i 's/^OTP_EMAIL_ENABLED=.*/OTP_EMAIL_ENABLED=true/' $APP_DIR/backend/.env
fi
grep -q "^OTP_EMAIL_ENABLED=" $APP_DIR/backend/.env || echo "OTP_EMAIL_ENABLED=true" >> $APP_DIR/backend/.env
grep -q "^RESEND_FROM_EMAIL=" $APP_DIR/backend/.env || echo "RESEND_FROM_EMAIL=no-reply@smartpayrolling.com" >> $APP_DIR/backend/.env
grep -q "^RESEND_API_KEY=re_" $APP_DIR/backend/.env || echo "RESEND_API_KEY=re_TVV9ccdZ_NiFrGwZzGjVTiKLEYSskpGqB" >> $APP_DIR/backend/.env
grep -q "^EMERGENT_LLM_KEY=" $APP_DIR/backend/.env || echo "EMERGENT_LLM_KEY=sk-emergent-6A80335Da3e07B3C5D" >> $APP_DIR/backend/.env

echo "==> 5/9 Installing backend deps..."
grep -v "^litellm" $APP_DIR/backend/requirements.txt > /tmp/reqs.txt
$PIP install -r /tmp/reqs.txt --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/ -q || \
  echo "   (pip failed — safe to continue if requirements unchanged)"
$PIP install openpyxl Pillow -q || true
echo "→ Warming up Face AI models (InsightFace buffalo_l — downloads ~300MB on first run)…"
$APP_DIR/backend/venv/bin/python - << 'PYW' || echo "   (model warmup failed — face features will retry lazily)"
from insightface.app import FaceAnalysis
app = FaceAnalysis(name="buffalo_l", allowed_modules=["detection", "recognition"],
                   providers=["CPUExecutionProvider"])
app.prepare(ctx_id=-1, det_size=(640, 640))
print("   Face AI models READY")
PYW

echo "==> 6/9 Restarting backend FIRST (portal comes back before the build)..."
echo "==> Seeding second super admin login (idempotent)..."
cd $APP_DIR/backend
$APP_DIR/backend/venv/bin/python seed_second_super_admin.py || python3 seed_second_super_admin.py || echo "⚠ SEED FAILED — run manually: cd $APP_DIR/backend && ./venv/bin/python seed_second_super_admin.py"

echo "==> Iter 629 migration: enable auto-approve for MOBILE/PWA punches on ALL firms..."
cd $APP_DIR/backend
$APP_DIR/backend/venv/bin/python - << 'PYMIG' || echo "⚠ migration failed — run manually"
import asyncio, os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
load_dotenv("/app/backend/.env" if os.path.exists("/app/backend/.env") else ".env")
load_dotenv(".env")
async def m():
    db = AsyncIOMotorClient(os.environ["MONGO_URL"])[os.environ.get("DB_NAME", "test_database")]
    r = await db.companies.update_many({}, {"$set": {"auto_approve_mobile_punches": True}})
    print(f"   auto_approve_mobile_punches=True set on {r.modified_count}/{r.matched_count} firms")
asyncio.run(m())
PYMIG

sudo supervisorctl stop sksharma-backend 2>/dev/null || true
sudo fuser -k 8001/tcp 2>/dev/null || true
sleep 2
sudo supervisorctl start sksharma-backend 2>/dev/null || sudo systemctl restart sksharma-backend 2>/dev/null || true
HEALTH=""
for i in $(seq 1 12); do
  sleep 5
  HEALTH=$(curl -s -m 8 http://localhost:8001/api/health)
  [ -n "$HEALTH" ] && break
  echo "   waiting for backend... (${i}0s)"
done
if [ -n "$HEALTH" ]; then
  echo "   Backend healthy ✅  ($HEALTH)"
else
  echo "   ❌ BACKEND STILL NOT ANSWERING. Last 30 log lines:"
  sudo tail -30 /var/log/supervisor/sksharma-backend*.log 2>/dev/null || sudo journalctl -u sksharma-backend -n 30 --no-pager 2>/dev/null
  echo "   ── Send me the lines above. Continuing with the web build anyway."
fi

echo "==> 7/9 Building web frontend (with OOM protection)..."
cd $APP_DIR/frontend
yarn install --frozen-lockfile --silent 2>/dev/null || yarn install --silent
export NODE_OPTIONS="--max-old-space-size=3072"
rm -rf dist
if npx expo export -p web 2>&1 | tail -15; then true; fi
if [ ! -f dist/index.html ] || [ ! -d dist/_expo/static/js/web ]; then
  echo "❌ WEB BUILD FAILED — the current live portal folder was NOT touched."
  echo "   Re-run this script once; if it fails again send me the build error above."
  exit 1
fi
echo "   Build OK ✅ ($(du -sh dist | cut -f1))"

echo "==> 8/9 Publishing new build (with rollback safety)..."
sudo mkdir -p $WEB_DIR
sudo rm -rf ${WEB_DIR}.prev
sudo cp -r $WEB_DIR ${WEB_DIR}.prev 2>/dev/null || true
sudo find $WEB_DIR -mindepth 1 -maxdepth 1 ! -name '.well-known' ! -name '_expo' -exec rm -rf {} +
sudo cp -r dist/* $WEB_DIR/
sudo cp public/sw.js $WEB_DIR/sw.js 2>/dev/null || true
sudo find $WEB_DIR/_expo -type f -mtime +45 -delete 2>/dev/null || true
sudo nginx -t && sudo systemctl reload nginx

echo "==> 9/9 Verification..."
echo -n "   Server badge is 644 (must say OK): "
grep -q 'APP_ITERATION = "644"' $APP_DIR/backend/server.py && echo "OK" || echo "MISSING!"
echo -n "   Toolbar polish — Iter 640 (must say OK): "
grep -q 'label renamed to just' $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Approve backlog endpoint — Iter 639 (must say OK): "
grep -q 'approve-all-pending' $APP_DIR/backend/routes/attendance_self_service.py && echo "OK" || echo "MISSING!"
echo -n "   Attendance grid fonts — Iter 639 (must say OK): "
grep -q 'scaled ~20% for larger fonts' $APP_DIR/frontend/app/attendance-grid.tsx && echo "OK" || echo "MISSING!"
echo -n "   Toolbar overlap fix — Iter 638 (must say OK): "
grep -q 'compact buttons, one line' $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Configure Batch toolbar — Iter 637 (must say OK): "
grep -q 'batchLine' $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Actual grid redesign + compact header — Iter 636 (must say OK): "
grep -q 'csr-setup-expand' $APP_DIR/frontend/app/compliance-salary-run.tsx && grep -q 'UI readability' $APP_DIR/frontend/app/salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Grid readability redesign — Iter 635 (must say OK): "
grep -q 'UI readability' $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   1-min autosave restored — Iter 634 (must say OK): "
grep -q 'AUTO-SAVE RESTORED' $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Tab-switch reload removed — Iter 634 (must say OK): "
grep -qv 'visibilitychange' $APP_DIR/frontend/src/hooks/usePwaAutoUpdate.ts && echo "OK" || echo "MISSING!"
echo -n "   Whole-rupee CALCULATION — Iter 633 (must say OK): "
grep -q 'ALWAYS CALCULATE IN ROUND FIGURES' $APP_DIR/backend/utils/compliance_salary.py && echo "OK" || echo "MISSING!"
echo -n "   Export Displayed button — Iter 633 (must say OK): "
grep -q 'export-display.xlsx' $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Whole-rupee exports — Iter 632 (must say OK): "
grep -q 'round_export_rows' $APP_DIR/backend/utils/compliance_salary.py && echo "OK" || echo "MISSING!"
echo -n "   Allowance disable warning — Iter 631 (must say OK): "
grep -q 'compliance-allowance-impact' $APP_DIR/frontend/app/firm-master.tsx && echo "OK" || echo "MISSING!"
echo -n "   Allowance mask inside engine — Iter 630 (must say OK): "
grep -q 'enabled_allowances: Optional' $APP_DIR/backend/utils/compliance_salary.py && echo "OK" || echo "MISSING!"
echo -n "   PWA punch auto-approve default — Iter 629 (must say OK): "
grep -q 'is not False' $APP_DIR/backend/routes/attendance_core.py && echo "OK" || echo "MISSING!"
echo -n "   ESS punch time display fix — Iter 629 (must say OK): "
grep -q 'timeZone: "UTC"' $APP_DIR/frontend/app/my-attendance.tsx && echo "OK" || echo "MISSING!"
echo -n "   Dummy Shift Matrix backend — Iter 628 (must say OK): "
grep -q 'dummy_map' $APP_DIR/backend/routes/inout_ot_matrix.py && echo "OK" || echo "MISSING!"
echo -n "   Dummy Shift Mode toggle UI — Iter 628 (must say OK): "
grep -q 'iom-dummy-toggle' $APP_DIR/frontend/app/inout-ot-matrix.tsx && echo "OK" || echo "MISSING!"
echo -n "   Shift Deployment Summary Only — Iter 627 (must say OK): "
grep -q '_summary_only' $APP_DIR/backend/routes/labour_reports.py && echo "OK" || echo "MISSING!"
echo -n "   Summary toggle UI — Iter 627 (must say OK): "
grep -q 'lr-data-summary' $APP_DIR/frontend/app/labour-reports.tsx && echo "OK" || echo "MISSING!"
echo -n "   Daily rate revisions — Iter 626 (must say OK): "
grep -q "_apply_daily_rate_revisions" $APP_DIR/backend/routes/compliance_salary_runs.py && echo "OK" || echo "MISSING!"
echo -n "   calc_detail audit — Iter 626 (must say OK): "
grep -q '"calc_detail"' $APP_DIR/backend/utils/compliance_salary.py && echo "OK" || echo "MISSING!"
echo -n "   Multi-branch module — Iter 624 (must say OK): "
grep -q "branch_mgmt_router" $APP_DIR/backend/server.py && echo "OK" || echo "MISSING!"
echo -n "   Punch branch authorization — Iter 624 (must say OK): "
grep -q "_branch_punch_gate" $APP_DIR/backend/routes/attendance_core.py && echo "OK" || echo "MISSING!"
echo -n "   Branch screens — Iter 624 (must say OK): "
[ -f $APP_DIR/frontend/app/branch-management.tsx ] && [ -f $APP_DIR/frontend/app/branch-dashboard.tsx ] && echo "OK" || echo "MISSING!"
echo -n "   Format 2 UAN/EPF wrap fix — Iter 623 (must say OK): "
grep -q 'idcell2' $APP_DIR/backend/utils/compliance_salary.py && echo "OK" || echo "MISSING!"
echo -n "   PF/ESIC proration LOCKED to Month Days — Iter 622 (must say OK): "
grep -q 'pf_proration_method = "calendar_days"' $APP_DIR/backend/utils/compliance_salary.py && echo "OK" || echo "MISSING!"
echo -n "   PF proration badge — Iter 621 (must say OK): "
grep -q "pf-proration-badge" $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   PF proration mirror in grid — Iter 620 (must say OK): "
grep -q "pfProrationFactor" $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Shortcuts Phase 3 — custom keys engine (must say OK): "
grep -q "applyOverride" $APP_DIR/frontend/src/utils/shortcuts.ts && echo "OK" || echo "MISSING!"
echo -n "   Shortcuts Phase 3 — Employee Master Alt+N (must say OK): "
grep -q '"employee-master"' $APP_DIR/frontend/app/admin.tsx && echo "OK" || echo "MISSING!"
echo -n "   Excel-style grid cells — Iter 618 (must say OK): "
grep -q "EditableGridCell" $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Arrow-key data-integrity guard (must say OK): "
grep -q "dirtyRef" $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   No-autosave + copy-verbatim (must say OK): "
grep -q "markGridDirty" $APP_DIR/frontend/app/compliance-salary-run.tsx && echo "OK" || echo "MISSING!"
echo -n "   Import ADVANCE→Advance col (must say OK): "
grep -q "actual_other_ded" $APP_DIR/backend/routes/compliance_salary_runs.py && echo "OK" || echo "MISSING!"
echo -n "   DOJ/DOL calendar window + audit (must say OK): "
grep -q "pay_days_audit" $APP_DIR/backend/routes/compliance_salary_runs.py && echo "OK" || echo "MISSING!"
echo -n "   Photo crop step in PWA (must say OK): "
grep -q "CropModal" $APP_DIR/frontend/app/profile-photo.tsx && echo "OK" || echo "MISSING!"
echo -n "   Punch face enforcement — Iter 615 (must say OK): "
grep -q "enforce_template_match" $APP_DIR/backend/routes/face_punch.py && echo "OK" || echo "MISSING!"
echo -n "   Web build published (must say OK): "
[ -f $WEB_DIR/index.html ] && echo "OK" || echo "MISSING!"
echo -n "   Backend /api/health: "
curl -s -m 5 http://localhost:8001/api/health || echo "❌ NOT ANSWERING"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  DONE — Iter 644 deployed."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): AUTO-SAVE RESTORED — the Compliance Salary sheet"
echo "    silently saves ALL work every 1 minute while there are"
echo "    unsaved edits (green Auto-saved HH:MM:SS indicator). The"
echo "    Actual Salary Process already saves each edit instantly and"
echo "    now RETRIES failed saves after 1 minute."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): MULTI-TAB FIX — switching back to an older browser"
echo "    tab NO LONGER reloads the app / kicks you to the Dashboard"
echo "    after a deploy (update now applies on next fresh open only)."
echo "    Closing/refreshing a tab with unsaved compliance edits now"
echo "    asks for confirmation first."
echo "  • ALSO (633): WHOLE-RUPEE CALCULATION — the compliance engine"
echo "    itself now calculates in round figures (gross, wage bases,"
echo "    PF/ESIC/PT/TDS, deductions, net) so a Reprocess never shows"
echo "    decimals again; totals are re-derived so columns tally."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): AUTO-SAVE RESTORED — the Compliance Salary sheet"
echo "    silently saves ALL work every 1 minute while there are"
echo "    unsaved edits (green Auto-saved HH:MM:SS indicator). The"
echo "    Actual Salary Process already saves each edit instantly and"
echo "    now RETRIES failed saves after 1 minute."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): MULTI-TAB FIX — switching back to an older browser"
echo "    tab NO LONGER reloads the app / kicks you to the Dashboard"
echo "    after a deploy (update now applies on next fresh open only)."
echo "    Closing/refreshing a tab with unsaved compliance edits now"
echo "    asks for confirmation first."
echo "  • ALSO (633): EXCEL (DISPLAYED) button on the Compliance sheet"
echo "    — exports EXACTLY what is on screen (incl. unsaved edits)"
echo "    BEFORE Save as Draft. Nothing is persisted by the export."
echo "  • ALSO (632): COMPLIANCE EXPORTS IN WHOLE RUPEES — the Excel /"
echo "    CSV Salary Sheet no longer prints paise (2903.85 -> 2904),"
echo "    so exported figures always MATCH the processed salary."
echo "    Days / hours / rates keep their real precision."
echo "  • NEW (631): DISABLE WARNING — switching OFF an allowance in"
echo "    Firm Master that has amounts in a processed month shows the"
echo "    month-wise impact (amount, employees, FINALIZED flag) and"
echo "    asks for confirmation before disabling."
echo "  • ALSO (630): ALLOWANCE ENABLE/DISABLE CONTRACT — disabling an"
echo "    editable allowance in Firm Master now calculates it as 0 on"
echo "    the NEXT Reprocess (Gross/ESIC/PT bases exclude it); stored"
echo "    values survive, re-enable + Reprocess restores them. On"
echo "    Freeze imports the masked amount moves into OT / Other"
echo "    Allowance so Gross Paid ALWAYS equals the imported gross"
echo "    and the columns add up. Basic is never masked."
echo "  • ALSO (629): PWA punch time FIXED — My Attendance was adding"
echo "    +5:30 twice (morning punch showed 3:27 PM). Now shows the"
echo "    exact punched wall-clock time. Correction requests fixed too."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): AUTO-SAVE RESTORED — the Compliance Salary sheet"
echo "    silently saves ALL work every 1 minute while there are"
echo "    unsaved edits (green Auto-saved HH:MM:SS indicator). The"
echo "    Actual Salary Process already saves each edit instantly and"
echo "    now RETRIES failed saves after 1 minute."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): MULTI-TAB FIX — switching back to an older browser"
echo "    tab NO LONGER reloads the app / kicks you to the Dashboard"
echo "    after a deploy (update now applies on next fresh open only)."
echo "    Closing/refreshing a tab with unsaved compliance edits now"
echo "    asks for confirmation first."
echo "  • ALSO (633): WHOLE-RUPEE CALCULATION — the compliance engine"
echo "    itself now calculates in round figures (gross, wage bases,"
echo "    PF/ESIC/PT/TDS, deductions, net) so a Reprocess never shows"
echo "    decimals again; totals are re-derived so columns tally."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): AUTO-SAVE RESTORED — the Compliance Salary sheet"
echo "    silently saves ALL work every 1 minute while there are"
echo "    unsaved edits (green Auto-saved HH:MM:SS indicator). The"
echo "    Actual Salary Process already saves each edit instantly and"
echo "    now RETRIES failed saves after 1 minute."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): ACTUAL SALARY grid got the same readability"
echo "    upgrade — 14px text, 14px bold headers, ~44px rows, larger"
echo "    edit cells, full viewport height, all employees one page."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): APPROVE BACKLOG — Punch Approvals now has a green"
echo "    Approve All Pending (N) button that clears the entire pending"
echo "    punch queue in ONE click (full audit trail on each record)."
echo "  • NEW (644): Salary Lock fixed — validation popup now always"
echo "    opens; INCENTIVE & custom allowance heads get own columns;"
echo "    OT columns follow the OVER TIME toggle."
echo "  • ALSO (643): Excel-import PF fix (Fixed 26, not 31); frozen"
echo "    page headers; note-chips row; 12px grid font."
echo "  • ALSO (642): Configure Batch filters — Month (FY-wise), Month"
echo "    Days, Employee Group + summary cards all on ONE line."
echo "  • ALSO (641): Salary Process button is now a compact two-line"
echo "    button matching Copy Last Month Salary."
echo "  • ALSO (640): Configure Batch polish — days field renamed to"
echo "    just MONTH DAYS with a narrow 2-digit input; Copy Last"
echo "    Month Salary is now a small two-line button."
echo "  • ALSO (639): ATTENDANCE GRID readability — names 14px, day"
echo "    cells 20% wider, IN/OUT times 12px, taller rows, larger"
echo "    headers/summary columns. View-only; no logic changes."
echo "  • ALSO (638): toolbar overlap FIXED — Month/FY selectors no"
echo "    longer collide with the Month-Days label; all 3 summary"
echo "    cards stay on the same line; Salary Process + Copy Last"
echo "    Month buttons are now compact side-by-side (not full-width)."
echo "  • ALSO (637): CONFIGURE BATCH single-line toolbar (VIEW-ONLY)"
echo "    — 22px title + gear icon, Month/FY/Days/Group in one row"
echo "    with display-only summary cards (Total blue / Processed"
echo "    green / Pending orange), GREEN Salary Process + purple"
echo "    Copy Last Month buttons, month-days notice in a light-blue"
echo "    info panel. No behaviour changes."
echo "  • ALSO (636): COMPACT HEADER — once a compliance run is on"
echo "    screen, the Select-firm + Configure-batch cards collapse"
echo "    into one slim bar (Firm · Month · Group | Change firm /"
echo "    month) so the grid starts right at the top. Tap to expand."
echo "  • ALSO (635): COMPLIANCE GRID READABILITY (VIEW-ONLY redesign)"
echo "    — 14px grid text, 14px bold headers, ~44px rows, wider"
echo "    auto-fit columns, right-aligned money, grid uses the full"
echo "    viewport height and ALL employees stay on ONE page with"
echo "    sticky headers. ZERO logic/calculation changes."
echo "  • ALSO (634): MULTI-TAB FIX — switching back to an older browser"
echo "    tab NO LONGER reloads the app / kicks you to the Dashboard"
echo "    after a deploy (update now applies on next fresh open only)."
echo "    Closing/refreshing a tab with unsaved compliance edits now"
echo "    asks for confirmation first."
echo "  • ALSO (633): EXCEL (DISPLAYED) button on the Compliance sheet"
echo "    — exports EXACTLY what is on screen (incl. unsaved edits)"
echo "    BEFORE Save as Draft. Nothing is persisted by the export."
echo "  • ALSO (632): COMPLIANCE EXPORTS IN WHOLE RUPEES — the Excel /"
echo "    CSV Salary Sheet no longer prints paise (2903.85 -> 2904),"
echo "    so exported figures always MATCH the processed salary."
echo "    Days / hours / rates keep their real precision."
echo "  • NEW (631): DISABLE WARNING — switching OFF an allowance in"
echo "    Firm Master that has amounts in a processed month shows the"
echo "    month-wise impact (amount, employees, FINALIZED flag) and"
echo "    asks for confirmation before disabling."
echo "  • ALSO (630): ALLOWANCE ENABLE/DISABLE CONTRACT — disabling an"
echo "    editable allowance in Firm Master now calculates it as 0 on"
echo "    the NEXT Reprocess (Gross/ESIC/PT bases exclude it); stored"
echo "    values survive, re-enable + Reprocess restores them. On"
echo "    Freeze imports the masked amount moves into OT / Other"
echo "    Allowance so Gross Paid ALWAYS equals the imported gross"
echo "    and the columns add up. Basic is never masked."
echo "  • ALSO (629): ALL employee PWA punches now AUTO-APPROVE by"
echo "    default (every firm). A firm can still turn this off via"
echo "    Firm Settings -> Auto-approve Mobile App Punches. Fake-GPS"
echo "    flagged punches still require manual approval."
echo "  • ALSO (628): DUMMY SHIFT IN/OUT MATRIX — open In/Out & OT"
echo "    Matrix and switch on the amber Dummy Shift Mode chip (only"
echo "    visible when the firm has Dummy Shift Allowed ON in the"
echo "    Attendance Policy). Present 2-punch days show the Dummy"
echo "    Shift master timings, WO/H markers follow Employee Master"
echo "    week-off + Holiday Master, overnight OUT is marked *."
echo "    100% READ-ONLY — attendance/payroll are never modified."
echo "  • ALSO (627): Shift Deployment Report now has a Data option —"
echo "    Full Data (all employee rows) or SUMMARY ONLY: Department-"
echo "    wise + Designation-wise totals (Deployed / Present / Half"
echo "    Day / Hours / OT / Cost) — screen, PDF, Excel & CSV."
echo "  • MULTI-BRANCH: Branches screen → ⚙ opens Branch Management"
echo "    (extended fields, employee home/authorized branches, temp"
echo "    assignments, transfers) and the Branch Dashboard with"
echo "    cost allocation. One payroll record per employee always."
echo "  • PF & ESIC now ALWAYS divide by the Month Days entered on the"
echo "    salary sheet — for ALL firms. Old method settings (÷26 etc.)"
echo "    are ignored; the options are removed from Compliance Settings."
echo "  • REPROCESS any sheet that showed ÷26 PF figures: PF becomes"
echo "    12% of the earned Wage Base (e.g. LAL CHAND 4333 → 520)."
echo "  • SHORTCUTS: press ? in the portal for the full list; click ✎"
echo "    on any row to set your own keys; Reset restores defaults."
echo "  • Alt+N = new record on Employee Master / Advances / Claims;"
echo "    Ctrl+S saves employee forms; Ctrl+F finds an employee."
echo "  • SALARY GRID (618): arrows only move between cells — they can"
echo "    never change a payroll figure. Type to edit,"
echo "    Enter commits + moves down, Escape cancels."
echo "  • Untouched cells are never marked as manual overrides."
echo "  Admins just need to hard-refresh the portal once (Ctrl+F5)."
echo "════════════════════════════════════════════════════════════"
