/**
 * Iter 530 (user request) — Quick User Manual (PDF) download screen.
 * SUPER ADMIN ONLY — professional client-facing manual with real
 * portal screenshots, generated by the backend on demand.
 */
import React, { useState } from "react";
import {
  ActivityIndicator, Platform, Pressable, ScrollView, StyleSheet, Text, View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Stack, Redirect } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

import { apiBinary } from "@/src/api/client";
import { useAuth } from "@/src/context/AuthContext";
import { colors } from "@/src/theme";

const SECTIONS = [
  "Login", "Dashboard", "Company / Firm Master", "Employee Master",
  "Attendance", "Biometric Punch", "Leave & ESIC Leave", "Overtime",
  "Salary Processing", "Compliance Salary", "Compliance vs Actual",
  "Deductions", "Payroll Finalization", "Salary Slip", "Bank Payment",
  "Reports", "Monthly Payroll Report", "Excel / PDF Export",
  "Troubleshooting", "Payroll Quick Workflow",
];

export default function UserManualScreen() {
  const { user, loading } = useAuth();
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");

  if (loading) return null;
  if (!user || user.role !== "super_admin") return <Redirect href="/" />;

  const download = async () => {
    setBusy(true);
    setErr("");
    try {
      const r = await apiBinary("/admin/user-manual.pdf");
      if (Platform.OS === "web" && r.webBlobUrl)
        window.open(r.webBlobUrl, "_blank");
    } catch (e: any) {
      setErr(e?.message || "Failed to generate the manual");
    } finally {
      setBusy(false);
    }
  };

  return (
    <SafeAreaView style={s.root} edges={["top"]}>
      <Stack.Screen options={{ title: "User Manual" }} />
      <ScrollView contentContainerStyle={{ padding: 16 }}>
        <View style={s.hero}>
          <Ionicons name="book-outline" size={34} color="#7DD3FC" />
          <Text style={s.heroTitle}>Payroll & Compliance Software</Text>
          <Text style={s.heroSub}>QUICK USER MANUAL (PDF)</Text>
          <Text style={s.heroDesc}>
            A modern, client-ready quick guide (~20 pages) with REAL portal
            screenshots — cover page, table of contents, numbered steps,
            screenshot callouts, compliance-vs-actual comparison and a
            one-page payroll workflow chart.
          </Text>
          <Pressable style={s.btn} onPress={download} disabled={busy}
            testID="manual-download">
            {busy ? <ActivityIndicator color="#fff" /> : (
              <>
                <Ionicons name="download-outline" size={16} color="#fff" />
                <Text style={s.btnTxt}>Generate & Open PDF</Text>
              </>
            )}
          </Pressable>
          {err ? <Text style={s.err}>{err}</Text> : null}
          <Text style={s.lock}>
            🔒 Super Admin only — other roles cannot access this document.
          </Text>
        </View>

        <Text style={s.secTitle}>What&apos;s inside</Text>
        <View style={s.chips}>
          {SECTIONS.map((x, i) => (
            <View key={x} style={s.chip}>
              <Text style={s.chipTxt}>{i + 1}. {x}</Text>
            </View>
          ))}
        </View>
        <Text style={s.note}>
          Tip: generate a fresh copy after major portal updates so the
          screenshots stay current, then share the PDF with your client.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  hero: {
    backgroundColor: "#0F3B5C", borderRadius: 16, padding: 22,
    alignItems: "center",
  },
  heroTitle: { color: "#fff", fontSize: 18, fontWeight: "800", marginTop: 8 },
  heroSub: {
    color: "#7DD3FC", fontSize: 12.5, fontWeight: "800", letterSpacing: 1.5,
    marginTop: 2,
  },
  heroDesc: {
    color: "#CBD5E1", fontSize: 12.5, lineHeight: 18, textAlign: "center",
    marginTop: 10, maxWidth: 560,
  },
  btn: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: "#0E7490", borderRadius: 10, paddingVertical: 12,
    paddingHorizontal: 22, marginTop: 16, minWidth: 200,
    justifyContent: "center",
  },
  btnTxt: { color: "#fff", fontWeight: "800", fontSize: 14 },
  err: { color: "#FCA5A5", marginTop: 10, fontSize: 12 },
  lock: { color: "#94A3B8", fontSize: 11, marginTop: 12 },
  secTitle: {
    fontSize: 15, fontWeight: "800", color: colors.onSurface, marginTop: 18,
    marginBottom: 8,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    backgroundColor: "#E0F2FE", borderRadius: 8, paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chipTxt: { color: "#0F3B5C", fontSize: 11.5, fontWeight: "700" },
  note: {
    color: colors.onSurfaceSecondary, fontSize: 12, marginTop: 14,
    lineHeight: 17,
  },
});
